# Generated by Django 4.2 on 2023-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='events',
            name='volunteer',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='MainApp.eventsmembers'),
        ),
    ]
