# Generated by Django 4.2 on 2023-06-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo_reports/%Y/%m/%d/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='classroom_number',
            field=models.ManyToManyField(related_name='classrooms', to='MainApp.classroomsnumber'),
        ),
        migrations.AlterField(
            model_name='events',
            name='volunteer',
            field=models.ManyToManyField(related_name='volunteers', to='MainApp.eventsmembers'),
        ),
        migrations.AddField(
            model_name='events',
            name='photo_report',
            field=models.ManyToManyField(to='MainApp.photoreport'),
        ),
    ]
