# Generated by Django 4.2 on 2023-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='volunteer',
            field=models.ManyToManyField(blank=True, to='MainApp.eventsmembers'),
        ),
    ]
