# Generated by Django 4.2 on 2023-06-19 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_photoreport_alter_events_classroom_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='photo_report',
        ),
        migrations.AddField(
            model_name='photoreport',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.events'),
        ),
    ]
