# Generated by Django 4.2 on 2023-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_events_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='volunteer',
            field=models.ManyToManyField(to='MainApp.eventsmembers'),
        ),
    ]
