# Generated by Django 4.0 on 2023-07-25 18:59

import MainApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_account_avatar'),
        ('MainApp', '0004_alter_events_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.account'),
        ),
        migrations.AddField(
            model_name='photoreport',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='image',
            field=models.ImageField(upload_to=MainApp.models.f),
        ),
    ]
