# Generated by Django 4.2 on 2023-05-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_events_classroom_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
