# Generated by Django 4.2 on 2023-05-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_alter_otps_code'),
        ('MainApp', '0007_delete_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building', to='Accounts.building'),
        ),
    ]
