# Generated by Django 4.0 on 2023-07-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_account_avatar'),
        ('MainApp', '0007_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='MainApp.subjects'),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('subject', 'Предметное'), ('methodist', 'Методическое')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='MainApp.eventcategory'),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer', to='Accounts.account'),
        ),
    ]
