# Generated by Django 4.0 on 2023-07-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_events_subject_events_type_alter_events_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('subject', 'Предметное'), ('methodist', 'Методическое')], default='subject', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='volunteer',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='MainApp.EventsMembers'),
        ),
    ]
