# Generated by Django 4.2 on 2023-05-19 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
