# Generated by Django 4.2 on 2023-05-19 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0011_alter_classroom_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomsNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='events',
            name='classroom_number',
        ),
        migrations.AddField(
            model_name='events',
            name='classroom_number',
            field=models.ManyToManyField(to='MainApp.classroomsnumber'),
        ),
    ]
