# Generated by Django 4.2 on 2023-05-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_classroomsnumber_alter_classroom_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
