# Generated by Django 4.2 on 2023-05-20 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_teacherinviteevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmembers',
            name='points',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
