# Generated by Django 4.0 on 2023-07-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_account_role'),
        ('PersonalArea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=244)),
                ('context', models.TextField(max_length=3000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
