# Generated by Django 4.2 on 2023-06-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.TextField(choices=[('admin', 'Администратор'), ('teacher', 'Учитель'), ('parent', 'Родитель'), ('student', 'Ученик'), ('methodist', 'Методист')], max_length=10, null=True),
        ),
    ]
