# Generated by Django 4.2 on 2023-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_account_age_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_volunteer',
        ),
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=623050),
        ),
    ]
