# Generated by Django 4.0 on 2023-08-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_account_peculiarity_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='peculiarity',
            field=models.CharField(blank=True, choices=[('handicapped', 'инвалидность'), ('autism', 'аутизм')], max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
            ],
        ),
    ]
