# Generated by Django 4.0 on 2023-08-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_account_peculiarity_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='session_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='connections',
            name='session_key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
