# Generated by Django 4.0 on 2023-08-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_connections_session_id_connections_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connections',
            name='session_id',
        ),
        migrations.AddField(
            model_name='connections',
            name='device_browser',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='connections',
            name='device_system',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
