# Generated by Django 4.2 on 2023-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_permission_remove_account_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='role',
            old_name='user_selected',
            new_name='can_select',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=286966),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AddField(
            model_name='role',
            name='perms',
            field=models.ManyToManyField(to='Accounts.perms'),
        ),
    ]
