# Generated by Django 4.0 on 2023-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_remove_connections_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
