# Generated by Django 4.2 on 2023-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_perms_rename_user_selected_role_can_select_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='perms',
        ),
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=232096),
        ),
        migrations.DeleteModel(
            name='Perms',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
