# Generated by Django 4.0 on 2023-08-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_connections_login_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connections',
            old_name='login_time',
            new_name='last_activity',
        ),
    ]
