# Generated by Django 4.2 on 2023-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_alter_otps_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_confirm',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.TextField(choices=[('admin', 'Администратор'), ('teacher', 'Учитель'), ('parent', 'Родитель'), ('student', 'Ученик')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=515085),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('can_select', models.BooleanField(default=False)),
                ('perms', models.ManyToManyField(to='Accounts.perms')),
            ],
        ),
    ]
