# Generated by Django 4.2 on 2023-05-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_perms_remove_account_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=711425),
        ),
    ]
