# Generated by Django 4.2 on 2023-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_alter_otps_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=284538),
        ),
    ]
