# Generated by Django 4.2 on 2023-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_remove_account_age_account_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=407923),
        ),
    ]
