# Generated by Django 4.2 on 2023-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0029_alter_otps_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=609613),
        ),
    ]
