# Generated by Django 4.2 on 2023-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0033_alter_otps_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='classroom',
        ),
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=285706),
        ),
    ]
