# Generated by Django 4.2 on 2023-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0034_remove_account_classroom_alter_otps_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=586985),
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permissions', models.ManyToManyField(to='Accounts.permissions')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(to='Accounts.roles'),
        ),
    ]
