# Generated by Django 4.2 on 2023-05-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0036_remove_account_role_alter_otps_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=608156),
        ),
        migrations.AlterField(
            model_name='roles',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='Accounts.permissions'),
        ),
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.roles'),
        ),
    ]
