# Generated by Django 4.2 on 2023-05-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0038_account_role_remove_account_roles_alter_otps_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=424890),
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
