# Generated by Django 4.2 on 2023-05-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0039_remove_roles_permissions_remove_account_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='code',
            field=models.IntegerField(default=786224),
        ),
    ]
